# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_academy_quest_development
  username: peemai          
  password: new_password_here
  host: localhost            
  port: 5432

test:
  <<: *default
  database: my_academy_quest_test
  username: peemai
  password: new_password_here
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: my_academy_quest_production
    username: my_academy_quest
    password: <%= ENV["MY_ACADEMY_QUEST_DATABASE_PASSWORD"] %>
    host: <%= ENV.fetch("MY_ACADEMY_QUEST_DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("MY_ACADEMY_QUEST_DATABASE_PORT", 5432) %>
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *primary_production
    database: my_academy_quest_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: my_academy_quest_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: my_academy_quest_production_cable
    migrations_paths: db/cable_migrate
